"""add_crop_metadata_and_hardware_fields

Revision ID: 4fed950a8174
Revises: ac2a0dfe892f
Create Date: 2026-09-13 01:04:10.513887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fed950a8174'
down_revision: Union[str, Sequence[str], None] = 'ac2a0dfe892f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commands', sa.Column('status', sa.String(), nullable=True))
    op.add_column('commands', sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('commands', sa.Column('received_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('commands', sa.Column('result', sa.String(), nullable=True))
    op.add_column('devices', sa.Column('hardware_id', sa.String(), nullable=True))
    op.add_column('devices', sa.Column('public_key', sa.String(), nullable=True))
    op.add_column('devices', sa.Column('status', sa.String(), nullable=True))
    op.add_column('fields', sa.Column('crop_type', sa.String(), nullable=True))
    op.add_column('fields', sa.Column('variety', sa.String(), nullable=True))
    op.add_column('fields', sa.Column('growth_stage', sa.String(), nullable=True))
    op.add_column('measurements', sa.Column('soil_adc', sa.Integer(), nullable=True))
    op.add_column('measurements', sa.Column('rain_adc', sa.Integer(), nullable=True))
    op.add_column('measurements', sa.Column('temperature_c', sa.Float(), nullable=True))
    op.add_column('measurements', sa.Column('humidity_percent', sa.Float(), nullable=True))
    op.add_column('measurements', sa.Column('soil_moisture_percent', sa.Integer(), nullable=True))
    op.add_column('measurements', sa.Column('target_moisture_percent', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('measurements', 'target_moisture_percent')
    op.drop_column('measurements', 'soil_moisture_percent')
    op.drop_column('measurements', 'humidity_percent')
    op.drop_column('measurements', 'temperature_c')
    op.drop_column('measurements', 'rain_adc')
    op.drop_column('measurements', 'soil_adc')
    op.drop_column('fields', 'growth_stage')
    op.drop_column('fields', 'variety')
    op.drop_column('fields', 'crop_type')
    op.drop_column('devices', 'status')
    op.drop_column('devices', 'public_key')
    op.drop_column('devices', 'hardware_id')
    op.drop_column('commands', 'result')
    op.drop_column('commands', 'received_at')
    op.drop_column('commands', 'sent_at')
    op.drop_column('commands', 'status')
    # ### end Alembic commands ###
